/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.9/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Android Library
    alias(libs.plugins.android.library)
    // Kotlin Android
    alias(libs.plugins.kotlin.android)
    
    // Aplly Dokka plugin
    alias(libs.plugins.dokka)
    
    // maven publish
    id("maven-publish")
}

android {
    namespace = "com.andihasan7.flashbar"
    compileSdk = 36
    
    defaultConfig {
        
        minSdk = 21
        consumerProguardFiles("consumer-rules.pro")
        
        
    }
    
    buildFeatures {
        viewBinding = true
        
    }
    
    buildTypes {
        release {
            isMinifyEnabled = false
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
        }
    }
    
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }
    
    kotlinOptions {
        jvmTarget = "11"
    }
}

afterEvaluate {
    publishing {
        publications {
            create<MavenPublication>("release") {
                from(components["release"])

                groupId = "com.github.hasanelfalakiy"
                artifactId = "flashbar"
                version = "1.0-SNAPSHOT"
            }
        }
    }
}

/*
repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}
*/
dependencies {
    
    implementation(libs.common.utilcode)

    implementation(libs.androidx.appcompat)
    implementation(libs.androidx.annotation)
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.constraintlayout)
    implementation(libs.google.material)
}

// Apply a specific Java toolchain to ease working on different environments.
/*java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
*/

tasks.dokkaHtml.configure {
    // custom dokka output directory
    outputDirectory.set(file("../docs"))
}

tasks.withType<org.jetbrains.dokka.gradle.DokkaTask>().configureEach {
    // Memisahkan member agar tampil menjadi tab
    pluginsMapConfiguration.set(
        mapOf("org.jetbrains.dokka.base.DokkaBase" to """{ "separateInheritedMembers": true }""")
    )
}
