/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.9/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    alias(libs.plugins.android.library)

    alias(libs.plugins.kotlin.android)

    // Apply the java-library plugin for API and implementation separation.
    //`java-library`
    
    // maven publish
	//`maven-publish`
}

android {
    namespace = "com.andihasan7.flashbar"
    compileSdk = 34
    
    defaultConfig {
        
        minSdk = 26
        
        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles("consumer-rules.pro")
        
        
    }
    
    buildFeatures {
        viewBinding = true
        
    }
    
    buildTypes {
        release {
            isMinifyEnabled = false
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
        }
    }
    
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }
    
    kotlinOptions {
        jvmTarget = "11"
    }
}

group = "com.andihasan7.flashbar"
version = "1.0.0"
/*
publishing {
	publications {
		create<MavenPublication>("Maven") {
			from(components["java"])
		}
	}
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}
*/
dependencies {
    // Use the Kotlin JUnit 5 integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit5")

    // Use the JUnit 5 integration.
    testImplementation(libs.junit.jupiter.engine)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
    
    implementation(libs.common.utilcode)

    implementation(libs.androidx.appcompat)
    implementation(libs.androidx.annotation)
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.constraintlayout)
    implementation(libs.google.material)

    //implementation(projects.core.resources)
}

// Apply a specific Java toolchain to ease working on different environments.
/*java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
*/